PROGRAM main
INTEGER ::parameter_n
REAL :: Gamma
 parameter_n = 4
 Gamma = 29.0

SUBROUTINE Fun(Z,ETA_GROUND,E)
REAL Z,ETA_GROUND,E
! For B-C Model
 E = (Gamma*(Z-ETA_GROUND))**(-parameter_n)
! return
END SUBROUTINE

SUBROUTINE INTEGRATION(ETA_GROUND,LOWBOUND,UPBOUND,LEN,SUM)
 IMPLICIT NONE
 REAL,INTENT(IN):: ETA_GROUND,LOWBOUND,UPBOUND,LEN
 REAL,INTENT(OUT):: SUM
 REAL:: Z
 INTEGER :: num,i

 SUM = ZERO

! DO WHILE(Z .ge. LOWBOUND .and. Z .le. UPBOUND )
!    SUM = SUM + Fun(Z,ETA_GROUND)*LEN
!    Z = Z + LEN
! ENDDO

  num = ceiling((UPBOUND-LOWBOUND)/LEN)

  DO i = 1, num
     Z = LOWBOUND+LEN*(i-1)
     CALL Fun(Z,ETA_GROUND,E)
     SUM = SUM + E*LEN
  ENDDO

END SUBROUTINE INTEGRATION

END PROGRAM


